services:
  fastapi:
    build:
      context: ./backend
    container_name: sabbath-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/data:/app/app/data  # ✅ this is critical
    env_file:
      - ./backend/.env
    restart: always