services:
  fastapi:
    build:
      context: ./backend
    container_name: sabbath-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/app:/app/app             # mounts all app files
      - ./backend/app/data:/app/app/data   # 🟢 specifically mounts lesson data
    restart: always